<!DOCTYPE html>

<html>


<?php

$cache = 0;
$cacheStr = '?baxza33';

if ($cache==0) $cacheStr = '?' . date('l jS \of F Y h:i:s A');

?>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Weatherscan</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link media="screen" type="text/css" rel="stylesheet" href="//cdn.aerisjs.com/aeris-interactive/assets/css/default/style.css">
	<link media="screen" type="text/css" rel="stylesheet" href="//api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.css">

	<link rel="stylesheet" href="css/style.css<?=$cacheStr ?>" />  

</head>

<body>

	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	
	
	<script type="text/javascript" src="//api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.js"></script>
	<script type="text/javascript" src="//cdn.aerisjs.com/aeris-interactive/aim-leaflet.js"></script>
	
	<script type="text/javascript" src="js/jplayer/jquery.jplayer.min.js"></script>
	<script src="http://cdn.date-fns.org/v2.0.0-alpha0/date_fns.min.js"></script>
	
	<script type="text/javascript" src="js/utils.js<?=$cacheStr ?>"></script>
	<script type="text/javascript" src="js/audio.js<?=$cacheStr ?>"></script>
	<script type="text/javascript" src="js/groupull.js<?=$cacheStr ?>"></script>
	<script type="text/javascript" src="js/dataManager.js<?=$cacheStr ?>"></script>
	<script type="text/javascript" src="js/loops.js<?=$cacheStr ?>"></script>
	<script type="text/javascript" src="js/weather.js<?=$cacheStr ?>"></script>

	

	<div id="main" class="container">
		
		<img id="template" src="images/template-4k.png" />		
	

		<div id="info-slides">
			<div class="info-slide radar-slide">
				<div class="info-header">
					<div>Local Doppler Radar
						<div class="radar-color-legend">Past 3 Hours<br>Light&nbsp;<img src="images/precip-legend.png" alt="Past 3 Hours" />&nbsp;Heavy</div>
					</div>
				</div>
				<div id="radar-1" class="map"></div>
			</div>
		</div>
		


		<div id="date-time">
			<div id="date"></div>
			<div id="time"></div>
		</div>
		
		<div id="city"></div>
		
		<div id="conditions-icon"></div>

		<div id="current-conditions">
			<div id="now">now</div>
			<div id="current-temp"></div>
			<div id="current-info"></div>
		</div>		
					
		<div id="minimap-title">PAST 3 HOURS</div>
		<div id="minimap"></div>
		<div id="logo-area"><img src="images/midco_logo.png"/></div>
		
		<div id="forecast-shadow">
			<div id="forecast-header">
				<div id="forecast-city"></div><div id="forecast-title"></div>
			</div>
			<div id="forecast-text"><div>Retrieving forecast data...</div></div>
			<div id="forecast-tiles"></div>
		</div>
		
		
		<div id="marquee1" class="marquee">
			<div id="marquee-container">
				<div id="marquee-now"><span class="track-info"></span></div>
				<!--div id="marquee-tonight"></div-->	
			</div>
		</div>
		<img id="arrow-img" src="images/NOW.png<?=$cacheStr ?>"/>
		
		<div id="marquee2" class="marquee"><div>
		You are watching an emulation of the Weatherscan IntelliStar system. Weatherscan is a digital cable and satellite television network that is owned by a consortium owned in turn by NBCUniversal and investment firms The Blackstone Group and Bain Capital. A spinoff of The Weather Channel, Weatherscan features uninterrupted local weather information in graphical format on a continuous loop that is generated by an IntelliStar unit installed at the cable provider's headend; unlike The Weather Channel, Weatherscan does not feature on-air talent of any kind.
		</div></div>
							
	</div>
	

<script type="text/javascript">
	
	$(function() {

		// set your mapbox access token
		L.mapbox.accessToken = 'pk.eyJ1Ijoic3dhbGRuZXIiLCJhIjoiY2o4ZGpjcnVvMHBhazMzcDVnanZmd2lobCJ9.Kr5329g4YyZIlnYfHNXRWA';	
		var aerisMapBuilder = new aeris.interactive.MapAppBuilder({			
			apiId: 'G99TzbQi5wXjWSLq7U0x3',
			apiSecret: 'wHjpONXg3Nlhh2u2GJuibDhRZWEcs5mMFsT6vuJd',
			el: '#radar-1',
			modules: {
				map: {
					baseLayer: new aeris.maps.layers.MapBox({
						mapBoxId: 'swaldner.306d8456'	 //'swaldner.4158bce2' //'swaldner.306d8456'					
					})
				},
				animation: {
				  speed: 100,
				  futureSpeed: 200,
				  from: new Date(Date.now() - 3600 * 4 * 1000),
				  to: new Date(Date.now()),
				  useBigTimeline: false,
				  boundsMenu:{
					min: [
					  {
						value: 1000 * 60 * 60,
						label: '1 hour ago'
					  },
					  {
						value: 1000 * 60 * 60 * 2,
						label: '2 hours ago'
					  },
					  {
						value: 1000 * 60 * 60 * 3,
						label: '3 hours ago'
					  }
					],
					max: [
					  {
						value: 1000 * 60 * 60,
						label: 'next 1 hour'
					  },
					  {
						value: 1000 * 60 * 60 * 2,
						label: 'next 2 hours'
					  },
					  {
						value: 1000 * 60 * 60 * 3,
						label: 'next 3 hours'
					  }
					]
				  }
				}
			  }				
			//}
		});
		aerisMapBuilder
			.start()
			.done(function() {
				$('i.aeris-playIcon.aeris-icon-play').click();
			   console.log('Aeris Interactive Maps is initialized.');
			})
			.fail(function(err) {
				console.error(err);
			});
	});


	
</script>

</body>
</html>
